 --- #YAML:1.0
 name: Video-FFmpeg
 abstract: Extract Video information using libavformat
 version: 0.47
 author:
   - Max Vohra <max@seattlenetworks.com>
 license: perl
 distribution_type: module
 requires:
   ExtUtils::MakeMaker: 0
   ExtUtils::PkgConfig: 0
 recommends:
   Pod::Text: 0
   YAML: 0.35
 build_requires:
   Test::More: 0
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Max Vohra using vim
